name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        user: unstoppabledomains
        filename: metrics.svg
        token: ${{ secrets.METRICS_PAT }}
        base: header, activity, community, repositories, metadata
        plugin_activity: yes
        plugin_activity_limit: 5
        plugin_activity_days: 7
        plugin_activity_filter: issue, pr, release, fork, review, ref/create
        plugin_followup: yes
        plugin_followup_sections: repositories
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: no